### ISSUE TITLE
Sketchily and Turbolinks

### ISSUE THREAD

**Issue by charlesx2013** [lml/sketchily#14]
Hi! I was wondering if I would be able to get Sketchily and Turbolinks to work together. The sketchily drawing surface currently won't load unless I refresh the page, even when I include jquery-turbolinks. Is there a fix for this? 

Thanks!

**Comment by Dantemss** [comment]
I tested sketchily with turbolinks and everything seems to be working properly. Closing this issue.
Please open a new one if you still have a failing test case.
